{
 "title": "Jenkins: Jobs MWT19",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jenkins Scheduler max wait time (total time scheduler waits for offer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_scheduler_p99)"
    }
   ]
  },
  {
   "title": "Number of Jenkins Masters",
   "type": "graph",
   "description": "# of Jenkins masters currently running in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jenkinsstatsd_jenkins_queue_size_value)"
    }
   ]
  },
  {
   "title": "Executors Total (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_executor_count_value)"
    }
   ]
  },
  {
   "title": "Max 99th Percentile Job Queuing Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_jenkins_job_queuing_duration_p99)",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  }
 ]
}